# Generated by Django 5.2.4 on 2025-08-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.TextField(default='https://media.istockphoto.com/id/2173059563/vector/coming-soon-image-on-white-background-no-photo-available.jpg?s=2048x2048&w=is&k=20&c=GAilX3-Ir93C0mTl0O77lWFjgYGGaY-hNPO1efZazz8='),
        ),
    ]
