# Generated by Django 5.2.4 on 2025-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='image',
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.CharField(choices=[('ACT', 'Action'), ('COM', 'Comedy'), ('DRM', 'Drama'), ('ADV', 'Adventure'), ('FAM', 'Family'), ('SCI', 'Sci-Fi'), ('HOR', 'Horror')], max_length=3),
        ),
    ]
