# Generated by Django 5.2.4 on 2025-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_show_image_alter_show_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Family', 'Family'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror')], max_length=20),
        ),
    ]
