# Generated by Django 5.2.4 on 2025-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_show_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(choices=[('TV', 'TV Show'), ('MV', 'Movie')], default='TV', max_length=2),
        ),
    ]
