# Generated by Django 5.2.4 on 2025-08-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(default='shows/default.jpg', upload_to='shows/'),
        ),
    ]
