# Generated by Django 5.2.4 on 2025-08-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_show_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('show', 'user_name')},
        ),
    ]
